spring:
#  profiles:
#    active: native
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/xiaocan1/springcloud_transactional/tree/master/config/src/main/resources/config-repo
#          native:
#            search-locations: file:///F:/softCode/git/springcloud/springcloud_transactional/config/src/main/resources/config-repo

server:
  port: 8081
  context-path: /

#management:
#  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
